# Generated by Django 3.2.21 on 2024-05-19 12:46

import ckeditor.fields
import course_partnerships.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_overviews", "0027_auto_20221102_1109"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Course Categories",
                "verbose_name_plural": "Course Categories",
            },
        ),
        migrations.CreateModel(
            name="Center",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=1024)),
                ("slug", models.SlugField(max_length=1024)),
                (
                    "logo",
                    models.ImageField(
                        help_text="Upload only image file with .png, .jpeg, .jpg extension. Recommended image size: W 240px * H 340px",
                        upload_to="center/",
                        validators=[course_partnerships.validators.validate_bannner_extension],
                        verbose_name="logo",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Upload only image file with .png, .jpeg, .jpg extension.",
                        null=True,
                        upload_to="center/",
                        validators=[course_partnerships.validators.validate_bannner_extension],
                        verbose_name="Banner",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Centers",
                "verbose_name_plural": "Centers",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=1024)),
                ("slug", models.SlugField(max_length=1024)),
                (
                    "logo",
                    models.ImageField(
                        help_text="Upload only image file with .png, .jpeg, .jpg extension. Recommended image size: W 240px * H 340px",
                        upload_to="partner/",
                        validators=[course_partnerships.validators.validate_bannner_extension],
                        verbose_name="logo",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Upload only image file with .png, .jpeg, .jpg extension.",
                        null=True,
                        upload_to="partner/",
                        validators=[course_partnerships.validators.validate_bannner_extension],
                        verbose_name="Banner",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Schools and Partners",
                "verbose_name_plural": "Schools and Partners",
            },
        ),
        migrations.CreateModel(
            name="EnhancedCourse",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("categories", models.ManyToManyField(to="course_partnerships.Category")),
                ("centers", models.ManyToManyField(to="course_partnerships.Center")),
                (
                    "course",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_overviews.courseoverview",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="center",
            name="partner",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course_partnerships.partner"),
        ),
    ]
