# Generated by Django 3.2.21 on 2024-05-24 18:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_partnerships", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enhancedcourse",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="enhancedcourse",
            name="centers",
        ),
        migrations.AddField(
            model_name="category",
            name="partner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="course_partnerships.partner"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="show_on_homepage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enhancedcourse",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="course_partnerships.category"
            ),
        ),
        migrations.AddField(
            model_name="enhancedcourse",
            name="center",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="course_partnerships.center"
            ),
        ),
        migrations.AlterField(
            model_name="center",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
