# Generated by Django 3.2.21 on 2024-05-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_partnerships", "0002_auto_20240524_1816"),
    ]

    operations = [
        migrations.AddField(
            model_name="enhancedcourse",
            name="partner",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(""), to="course_partnerships.partner"),
        ),
        migrations.AlterField(
            model_name="enhancedcourse",
            name="category",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(""), to="course_partnerships.category"),
        ),
        migrations.AlterField(
            model_name="enhancedcourse",
            name="center",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(""), to="course_partnerships.center"),
        ),
    ]
