# Generated by Django 3.2.21 on 2024-07-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_partnerships", "0003_auto_20240527_1728"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="activate_school_admin",
            field=models.BooleanField(default=False),
        ),
    ]
