# Generated by Django 4.2.19 on 2025-07-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_partnerships', '0005_partnerorganizationmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganizationmapping',
            name='display_name',
            field=models.CharField(blank=True, help_text='Custom name to display for the partner in this specific mapping.', max_length=255, null=True),
        ),
    ]
