# Generated by Django 4.2.19 on 2025-11-18 08:33

import course_partnerships.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_partnerships', '0006_partnerorganizationmapping_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, help_text='Full name of the course creator', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Professional title or designation (e.g., Professor, Senior Instructor)', max_length=255, null=True)),
                ('experience', models.PositiveIntegerField(blank=True, help_text='Years of experience (e.g., 5)', null=True)),
                ('bio', models.TextField(blank=True, help_text='Detailed biography of the course creator (max 2000 characters)', max_length=2000, null=True, verbose_name='Biography')),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload only image file with .png, .jpeg, .jpg extension.', null=True, upload_to='course_creators/', validators=[course_partnerships.validators.validate_bannner_extension], verbose_name='Profile Picture')),
                ('partner', models.ForeignKey(help_text='School/Partner this course creator is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='course_creators', to='course_partnerships.partner')),
            ],
            options={
                'verbose_name': 'Course Creator',
                'verbose_name_plural': 'Course Creators',
            },
        ),
    ]
