# Generated by Django 5.2.7 on 2026-08-18 11:05

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        ('course_partnerships', '0009_alter_partner_logo_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers are shown first. Only the first two active picks are used.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire a pick without deleting it.')),
                ('course', models.OneToOneField(db_constraint=False, help_text='Course to feature in the homepage hero.', on_delete=django.db.models.deletion.CASCADE, to='course_overviews.courseoverview')),
            ],
            options={
                'verbose_name': 'Homepage Hero Course',
                'verbose_name_plural': 'Homepage Hero Courses',
                'ordering': ('order', 'id'),
            },
        ),
    ]
