# Generated by Django 5.2.7 on 2026-08-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_partnerships', '0010_herocourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocourse',
            name='new_until',
            field=models.DateField(blank=True, help_text="Show a 'New course' badge on this course's hero card up to and including this date. Leave blank for no badge.", null=True),
        ),
    ]
