# Generated by Django 5.2.7 on 2026-09-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_partnerships', '0011_herocourse_new_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herocourse',
            name='new_until',
            field=models.DateField(blank=True, help_text="Show a 'New course' badge until this date. Leave blank for none. Independent of 'is active'.", null=True),
        ),
    ]
